### ISSUE TITLE
No logo data produces empty logo tag in generated SAML metadata

### ISSUE THREAD

**Issue by zamzterz** [IdentityPython/SATOSA#23] opened 2016-09-08 11:53 UTC
If no logo is specified for the OIDC backend it still produces a logo tag in the SAML metadata.
This makes the SAML metadata invalid, url inside the logo tag is not allowed to be empty.

**Comment by jkakavas** [comment] 2017-05-05 15:11
I guess this should be opened against pysaml2, which is used for the metadata generation. 
https://github.com/rohe/pysaml2/blob/master/src/saml2/metadata.py#L285

```python
if isinstance(val, dict):
    logo = mdui.Logo()
    for attr, value in val.items():
        if attr in logo.keys():
            setattr(logo, attr, value)
    inst.append(logo)
```

should be changed to something like

```python
if isinstance(val, dict):
    if val.items():
        logo = mdui.Logo()
        for attr, value in val.items():
            if attr in logo.keys():
                setattr(logo, attr, value)
        inst.append(logo)
```

I'm tempted to close this unless @zamzterz has any objections.

**Comment by leifj** [comment] 2017-05-07 21:30
I agree this should be solved in pysaml2 - I stuggest giving @rohe a pull request

**Comment by jkakavas** [comment] 2017-05-08 06:09
Will do.

**Comment by jkakavas** [comment] 2017-05-08 07:04
Actually, I can't even reproduce the bug. Neither in a test satosa config nor in pySAML2 directly ( i.e. using https://github.com/rohe/pysaml2/blob/master/tests/test_83_md_extensions.py )

**Comment by jkakavas** [comment] 2017-05-15 11:52
@zamzterz Samuel, any ideas on how to reproduce this or further details ?

**Comment by mrvanes** [comment] 2018-05-14 08:13
We had the same problem, but it was due to a configuration syntax error (wrong keyword assumption). One way to cause this is like this:
```
    service:
      idp:
        name: Proxy IdP
        ui_info:
          logo:
            url: "http://idp.logo.url/"
            width: "100"
            height: "100"
```
The problem is that keyword ```url``` should be ```text```. One could argue that pysaml should either raise an exception or refuse to create the logo element without a valid ```text``` key.

**Closed** 2018-09-21 21:39 UTC
